name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: PDESystemLibrary.jl, group: NeuralPDE}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "1"
      julia-arch: "x64"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
