name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  downgrade:
    strategy:
      matrix:
        group:
          - NNPDE1
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "1.10"
      group: "${{ matrix.group }}"
      skip: "Pkg,TOML"
      allow-reresolve: true
    secrets: "inherit"
