name: "GPU Tests"

on:
  pull_request:
    branches:
      - master
      - 'release-'
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  cuda-tests:
    name: "CUDA Tests"
    runs-on: [self-hosted, Linux, X64, gpu]
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: "CUDA"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  gpu-docs:
    name: "Documentation"
    runs-on: [self-hosted, Linux, X64, gpu]
    timeout-minutes: 360
    if: github.event_name == 'push' || !github.event.pull_request.draft
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - run: |
          julia --project=docs -e '
            println("--- Instantiating project")
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            println("+++ Building documentation")
            include("docs/make.jl")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          DATADEPS_ALWAYS_ACCEPT: true
